[build]
  base = "site/"
  command = "hugo --gc --minify --baseUrl $DEPLOY_PRIME_URL"
  publish = "/public"

[context.production.environment]
HUGO_VERSION = "0.82.1"

[context.deploy-preview.environment]
HUGO_VERSION = "0.82.1"
